name: Bug report
description: Fill out a bug report to help us improve Statamic.
body:
  - type: textarea
    attributes:
      label: Bug description
      description: What happened? What did you expect to happen?
      placeholder: I did this thing over here, and saw this error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to reproduce
      description: List the steps so we're able to recreate this bug. Bonus points if you can provide an example GitHub repo with this bug reproduced.
      placeholder: Go here, Type this, Click that, Look over there.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Environment
        You can get the versions and installed addons by running `php please support:details`.
  - type: input
    attributes:
      label: Statamic version
      placeholder: e.g. 3.2.15
    validations:
      required: true
  - type: input
    attributes:
      label: Laravel version
      placeholder: e.g. 8.64.0
    validations:
      required: true
  - type: input
    attributes:
      label: PHP version
      placeholder: e.g. 8.0.1
    validations:
      required: true
  - type: textarea
    attributes:
      label: Installed Addons
  - type: dropdown
    attributes:
      label: Installation
      description: How did you install Statamic?
      options:
        - Blank statamic/statamic site using the CLI tool
        - Starter Kit using the CLI tool
        - Existing Laravel app
        - Other (please explain)
    validations:
      required: true      
  - type: input
    attributes:
      label: Other
      description: Fancy installation method? Please explain!
