name: Bug report
description: Fill out a bug report to help us improve Statamic.
body:
  - type: textarea
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
      placeholder: I did this thing over here, and saw this error...
    validations:
      required: true
  - type: input
    attributes:
      label: Statamic Version
      placeholder: 3.2.x
    validations:
      required: true